import fs from "fs";
import path from "path";
import type { ServerRouteEntry } from "./scan.js";

export function generateServerRoutes(appRoot: string, routes: ServerRouteEntry[]): string {
  const outDir = path.resolve(appRoot, "./.anaemia");
  const outPath = path.resolve(outDir, "./__anaemia_server_routes__.ts");

  const imports = routes.map((r, i) => `import * as ServerRoute${i} from "${r.filePath}";`).join("\n");

  const registrations = routes.map((r, i) => `  registerRoute(app, "${r.urlPattern}", ServerRoute${i});`).join("\n");

  const code = `
// @ts-nocheck
// auto-generated by anaemia - do not edit!!
import type { Hono } from "hono";

${imports}

function registerRoute(app: any, pattern: string, mod: any) {
  const methods = ["GET", "POST", "PUT", "PATCH", "DELETE"];
  for (const m of methods) {
    if (m in mod && typeof mod[m] === "function") {
      app[m.toLowerCase()](pattern, mod[m]);
    }
  }
}

export function registerServerRoutes(app: Hono) {
${registrations}
}
`.trimStart();

  fs.writeFileSync(outPath, code);
  return outPath;
}
