import fs from "node:fs";
import path from "node:path";
import type { ServerRouteEntry } from "./scan.js";
import { transform } from "sucrase";

export function generateServerRoutes(appRoot: string, routes: ServerRouteEntry[]): string {
  const outDir = path.resolve(appRoot, "./.anaemia");
  const isTs = fs.existsSync(path.resolve(appRoot, "tsconfig.json"));
  const ext = isTs ? "ts" : "js";
  const outPath = path.resolve(outDir, "./__anaemia_server_routes__." + ext);

  const imports = routes.map((r, i) => `import * as ServerRoute${i} from "${r.filePath}";`).join("\n");

  const registrations = routes.map((r, i) => `  registerRoute(app, "${r.urlPattern}", ServerRoute${i});`).join("\n");

  const rawCode = `
// @ts-nocheck
// auto-generated by anaemia - do not edit!!
${imports}

function registerRoute(app: any, pattern: string, mod: any) {
  const methods = ["GET", "POST", "PUT", "PATCH", "DELETE"];
  for (const m of methods) {
    if (m in mod && typeof mod[m] === "function") {
      app[m.toLowerCase()](pattern, mod[m]);
    }
  }
}

export function registerServerRoutes(app: Hono) {
${registrations}
}
`.trimStart();

  const finalCode = isTs
    ? rawCode
    : transform(rawCode.replace("// @ts-nocheck\n", ""), {
        transforms: ["typescript", "jsx"],
        jsxRuntime: "preserve",
        production: true,
      }).code;

  fs.writeFileSync(outPath, finalCode);
  return outPath;
}
